USE sucos; 

CREATE TABLE tabela_de_vendedores (
MATRICULA varchar(5),
NOME varchar(100),
PERCENTUAL_COMISSAO float,
DATA_ADMISSAO date,
DE_FERIAS bit);


ALTER TABLE tabela_de_vendedores ADD PRIMARY KEY (MATRICULA);


INSERT INTO tabela_de_vendedores (
MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS)
VALUES ('00235', 'Márcio Almeida Silva', 0.08 , '2014-08-15', 0);

INSERT INTO tabela_de_vendedores (
MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS)
VALUES ('00236', 'Cláudia Morais', 0.08 , '2013-09-17', 1);

INSERT INTO tabela_de_vendedores (
MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS)
VALUES ('00237', 'Roberta Martins', 0.11 , '2017-03-08', 1);

INSERT INTO tabela_de_vendedores (
MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS)
VALUES ('00238', 'Péricles Alves', 0.11 , '2016-08-21', 0);


SELECT * FROM tabela_de_vendedores;
