Use sucos;

SELECT * FROM tbcliente WHERE YEAR(DATA_NASCIMENTO) = 1995;

SELECT * FROM tbcliente WHERE DATA_NASCIMENTO >= '1997-01-06';

SELECT * FROM tabela_de_vendedores WHERE MATRICULA >= 2016;

SELECT * FROM tbproduto WHERE PRECO_LISTA >= 16.009 AND PRECO_LISTA <= 16.007;

SELECT * FROM tbcliente WHERE DATA_NASCIMENTO <= 2004 AND IDADE >= 18; 

SELECT * FROM tbcliente WHERE CIDADE = 'Rio de Janeiro' OR BAIRRO = 'Jardins'; 

SELECT * FROM tbcliente WHERE (IDADE <= 24 AND IDADE >=32 AND DATA_NASCIMENTO > 1997); 

SELECT * FROM TABELA_DE_VENDEDORES WHERE YEAR (DATA_ADMISSAO) < 2016 AND DE_FERIAS = 1;