USE sucos;

ALTER TABLE tbproduto ADD PRIMARY KEY (PRODUTO);

SELECT * FROM tbproduto;

INSERT INTO tbproduto (
PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
VALUES ('1078680', 'Frescor do Verão - 470- ml - Manga', 'LATA', '470 ml', 'Manga',  5.18);

UPDATE tbproduto SET EMBALAGEM = 'GARRAFA'
WHERE PRODUTO = '1078680'; 

SELECT * FROM tbproduto;