

CREATE TABLE tbCliente2
(CPF VARCHAR(11),
NOME VARCHAR(100),
ENDERECO01 VARCHAR(150),
ENDERECO02 VARCHAR(150),
BAIRRO VARCHAR(50),
CIDADE VARCHAR(50),
ESTADO VARCHAR(50),
CEP VARCHAR(8),
IDADE SMALLINT,
SEXO VARCHAR(1),
LIMITE_CREDITO FLOAT,
VOLUME_COMPRA FLOAT,
PRIMEIRA_COMPRA BIT(1))

CREATE TABLE tbCliente3
(CPF VARCHAR(11),
NOME VARCHAR(100),
ENDERECO01 VARCHAR(150),
ENDERECO02 VARCHAR(150),
BAIRRO VARCHAR(50),
CIDADE VARCHAR(50),
ESTADO VARCHAR(50),
CEP VARCHAR(8),
IDADE SMALLINT,
SEXO VARCHAR(1),
LIMITE_CREDITO FLOAT,
VOLUME_COMPRA FLOAT,
PRIMEIRA_COMPRA BIT(1))